package com.intern.testcases;

import com.intern.base.TestBase;
import com.intern.pages.*;
import com.intern.util.NavigationBar;
import com.intern.util.ScrollDown;
import com.intern.util.ScrollUp;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import java.io.IOException;

public class TestCaseMix extends TestBase {
    private CarouselPage carouselPage;
    private OnboardingPage onboardingPage;
    private FormloginPage formloginPage;
    private HomePage homePage;
    private NotifPage notifPage;
    private FeedPage feedPage;
    private DiscoverPage discoverPage;
    private ProfilePage profilePage;
    private NavigationBar navigationBar;
    private ScrollDown scrollDown;
    private ScrollUp scrollUp;
    private Addpost addpost;

    public TestCaseMix() {
        super();
    }

    @BeforeMethod
    public void setup() throws IOException, InterruptedException{
        initialization();
        carouselPage = new CarouselPage();
        onboardingPage = new OnboardingPage();
        formloginPage = new FormloginPage();
        homePage = new HomePage();
        notifPage = new NotifPage();
        feedPage = new FeedPage();
        discoverPage = new DiscoverPage();
        profilePage = new ProfilePage();
        navigationBar = new NavigationBar();
        scrollDown = new ScrollDown();
        scrollUp = new ScrollUp();
        addpost = new Addpost();
    }

    @AfterMethod
    public void tearDown(){
        driver.quit();
    }

    @Test
    public void testMix() throws InterruptedException {
        carouselPage.tapNextBtn();
        carouselPage.tapNextBtn();
        carouselPage.tapStartBtn();
        onboardingPage.tapLoginBtn();
        formloginPage.prosesLogin(prop.getProperty("username"), prop.getProperty("password"));
        homePage.tapXBtn();
        notifPage.tapNotifBtn();
        homePage.tapBackBtn();
        notifPage.tapNotifBtn();
        homePage.tapBackBtn();
        navigationBar.tabBtnNavPlus();
        addpost.tapAddpostBtn();
        addpost.tapTakephotoBtn();
        addpost.tapCeklisBtn();
        addpost.tapOkBtn();
        addpost.prosescapt("Test");
        addpost.tapTagBtn();
        addpost.tapCekbocBtn();
        addpost.tapCeklistagBtn();
        addpost.tapOK2Btn();
        addpost.tapCeklisBtn();
        //navigationBar.tabBtnNavFeed();
        navigationBar.tabBtnNavHome();
        navigationBar.tabBtnNavFeed();
        Thread.sleep(3000);
        scrollDown.ScrollDown();
        scrollDown.ScrollDown();
        feedPage.tapLikeBtn();
        navigationBar.tabBtnNavDiscover();
        discoverPage.tapPostdiscoBtn();
        Thread.sleep(2000);
        scrollDown.ScrollDown();
        discoverPage.tapLikeBtn();
        discoverPage.tapBackdBtn();
        navigationBar.tabBtnNavHome();
        navigationBar.tabBtnNavFeed();
        Thread.sleep(3000);
        navigationBar.tabBtnNavHome();
        notifPage.tapNotifBtn();
        notifPage.tapPostnotifBtn();
        notifPage.tapComentBtn();
        notifPage.prosescoment("Tess");
        notifPage.tapPostcomentBtn();
        notifPage.tapBackBtn();
        notifPage.tapUsercommentBtn();
        homePage.tapBackBtn();
        notifPage.tapBackBtn();
        homePage.tapBackBtn();
        notifPage.tapNotifBtn();
        homePage.tapBackBtn();
        notifPage.tapNotifBtn();
        homePage.tapBackBtn();
        navigationBar.tabBtnNavDiscover();
        navigationBar.tabBtnNavHome();
        notifPage.tapNotifBtn();
        notifPage.tapPostnotifBtn();
        notifPage.tapComentBtn();
        notifPage.prosescoment("Tess");
        notifPage.tapPostcomentBtn();
        homePage.tapBackBtn();
        homePage.tapBackBtn();
        homePage.tapBackBtn();
        notifPage.tapNotifBtn();
        notifPage.tapPostnotifBtn();
        notifPage.tapComentBtn();
        notifPage.prosescoment("Tess");
        notifPage.tapPostcomentBtn();
        homePage.tapBackBtn();
        homePage.tapBackBtn();
        homePage.tapBackBtn();
        notifPage.tapNotifBtn();
        homePage.tapBackBtn();
        notifPage.tapNotifBtn();
        homePage.tapBackBtn();
        notifPage.tapNotifBtn();
        homePage.tapBackBtn();
        navigationBar.tabBtnNavFeed();
        Thread.sleep(2000);
        scrollDown.ScrollDown();
        feedPage.tapLikeBtn();
        navigationBar.tabBtnNavHome();
        notifPage.tapNotifBtn();
        homePage.tapBackBtn();
        notifPage.tapNotifBtn();
        homePage.tapBackBtn();
        notifPage.tapNotifBtn();
        notifPage.tapPostnotifBtn();
        notifPage.tapComentBtn();
        notifPage.prosescoment("Tess");
        notifPage.tapPostcomentBtn();
        homePage.tapBackBtn();
        homePage.tapBackBtn();
        homePage.tapBackBtn();
        notifPage.tapNotifBtn();
        homePage.tapBackBtn();
        navigationBar.tabBtnNavDiscover();
        navigationBar.tabBtnNavHome();
        navigationBar.tabBtnNavDiscover();
        navigationBar.tabBtnNavHome();
        notifPage.tapNotifBtn();
        homePage.tapBackBtn();
        navigationBar.tabBtnNavDiscover();
        discoverPage.tapPostdiscoBtn();
        discoverPage.tapLikeBtn();
        discoverPage.tapUserBtn();
        Thread.sleep(3000);
        scrollDown.ScrollDown();
        discoverPage.tapPostBtn();
        Thread.sleep(3000);
        scrollDown.ScrollDown();
        discoverPage.tapLikeBtn();
        homePage.tapBackBtn();
        homePage.tapBackBtn();
        homePage.tapBackBtn();
        navigationBar.tabBtnNavHome();
        notifPage.tapNotifBtn();
        notifPage.tapPostnotifBtn();
        notifPage.tapComentBtn();
        notifPage.prosescoment("Tess");
        notifPage.tapPostcomentBtn();
        homePage.tapBackBtn();
        homePage.tapBackBtn();
        homePage.tapBackBtn();
        navigationBar.tabBtnNavProfile();
        profilePage.tapPostBtn();
        profilePage.tapOption();
        profilePage.tapDelete();
        profilePage.tapYes();
        homePage.tapBackBtn();
        navigationBar.tabBtnNavFeed();
        navigationBar.tabBtnNavFeed();
        Thread.sleep(5000);
        scrollDown.ScrollDown();
        scrollDown.ScrollDown();
        scrollDown.ScrollDown();
        scrollDown.ScrollDown();
        scrollDown.ScrollDown();
        scrollDown.ScrollDown();
        scrollDown.ScrollDown();
        feedPage.tapItemBtn();
        homePage.tapBackBtn();
        feedPage.tapUserBtn();
        feedPage.tapPostBtn();
        feedPage.tapLikeBtn();
        homePage.tapBackBtn();
        homePage.tapBackBtn();
        navigationBar.tabBtnNavHome();
        Thread.sleep(2000);
        navigationBar.tabBtnNavFeed();
        navigationBar.tabBtnNavHome();
        notifPage.tapNotifBtn();
        notifPage.tabBtnNavUser();
        notifPage.tapPostBtn();
        notifPage.tapLikeBtn();
        homePage.tapBackBtn();
        homePage.tapBackBtn();
        homePage.tapBackBtn();
        notifPage.tapNotifBtn();
        homePage.tapBackBtn();
        notifPage.tapNotifBtn();
        notifPage.tapPostnotifBtn();
        notifPage.tapComentBtn();
        notifPage.prosescoment("Tess");
        notifPage.tapPostcomentBtn();
        homePage.tapBackBtn();
        homePage.tapBackBtn();
        homePage.tapBackBtn();
        notifPage.tapNotifBtn();
        notifPage.tapPostnotifBtn();
        notifPage.tapComentBtn();
        notifPage.prosescoment("Tess");
        notifPage.tapPostcomentBtn();
        homePage.tapBackBtn();
        homePage.tapBackBtn();
        notifPage.tabBtnNavUser();
        notifPage.tapPostBtn();
        notifPage.tapLikeBtn();
        homePage.tapBackBtn();
        homePage.tapBackBtn();
        homePage.tapBackBtn();
        scrollDown.ScrollDown();
        scrollDown.ScrollDown();
        scrollDown.ScrollDown();
        homePage.tapArtikelBtn();
        homePage.tapBackBtn();
        navigationBar.tabBtnNavFeed();
        scrollDown.ScrollDown();
        feedPage.tapLikeBtn();
        feedPage.tapUserBtn();
        homePage.tapBackBtn();
        navigationBar.tabBtnNavHome();
        notifPage.tapNotifBtn();
        homePage.tapBackBtn();
        navigationBar.tabBtnNavDiscover();
        discoverPage.tapPostdiscoBtn();
        discoverPage.tapLikeBtn();
        homePage.tapBackBtn();
        navigationBar.tabBtnNavHome();
        notifPage.tapNotifBtn();
        notifPage.tapUserBtn();
        homePage.tapBackBtn();
        homePage.tapBackBtn();
        navigationBar.tabBtnNavDiscover();
        discoverPage.tapPostdiscoBtn();
        discoverPage.tapUserBtn();
        Thread.sleep(2000);
        scrollDown.ScrollDown();
        discoverPage.tapPostBtn();
        discoverPage.tapLikeBtn();
        homePage.tapBackBtn();
        homePage.tapBackBtn();
        homePage.tapBackBtn();
        navigationBar.tabBtnNavHome();
        notifPage.tapNotifBtn();
        notifPage.tapUserBtn();
        Thread.sleep(3000);
        scrollDown.ScrollDown();
        homePage.tapBackBtn();
        homePage.tapBackBtn();
        navigationBar.tabBtnNavProfile();
        profilePage.tapBpointBtn();
        profilePage.tapWhatBtn();
        profilePage.tapHowBtn();
        homePage.tapBackBtn();
        navigationBar.tabBtnNavFeed();
        scrollDown.ScrollDown();
        scrollDown.ScrollDown();
        scrollDown.ScrollDown();
        scrollDown.ScrollDown();
        scrollDown.ScrollDown();
        scrollDown.ScrollDown();
        feedPage.tapItemBtn();
        Thread.sleep(3000);
        scrollDown.ScrollDown();
        feedPage.tapRevitemBtn();
        homePage.tapBackBtn();
        homePage.tapBackBtn();
        navigationBar.tabBtnNavDiscover();
        discoverPage.tapPostdiscoBtn();
        discoverPage.tapCommentBtn();
        discoverPage.prosescoment("Test");
        discoverPage.tapPostcommentBtn();
        homePage.tapBackBtn();
        homePage.tapBackBtn();
        navigationBar.tabBtnNavHome();
        notifPage.tapNotifBtn();
        homePage.tapBackBtn();
        notifPage.tapNotifBtn();
        homePage.tapBackBtn();
        notifPage.tapNotifBtn();
        notifPage.tapUserBtn();
        Thread.sleep(5000);
    }
}
